import { promisify } from 'node:util';
import { execFile as _execFile } from 'node:child_process';
import { readFileSync } from 'node:fs';
import type pino from 'pino';
import { createLogger } from '../../core/logger.js';

const defaultExecFile = promisify(_execFile);

type ExecFn = (cmd: string, args: string[], opts?: { cwd?: string }) => Promise<{ stdout: string; stderr: string }>;

export interface PRCreator {
  createPR(workspace_path: string, branch: string, spec_path: string): Promise<string>;
}

interface GHPRCreatorOptions {
  logDestination?: pino.DestinationStream;
}

function extractSpecTitle(specContent: string): string {
  const match = specContent.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : 'spec';
}

export class GHPRCreator implements PRCreator {
  private readonly execFn: ExecFn;
  private readonly logger: pino.Logger;

  constructor(execFn?: ExecFn, options?: GHPRCreatorOptions) {
    this.execFn = execFn ?? defaultExecFile;
    this.logger = createLogger('pr-creator', { destination: options?.logDestination });
  }

  async createPR(workspace_path: string, branch: string, spec_path: string): Promise<string> {
    const specContent = readFileSync(spec_path, 'utf-8');
    const specTitle = extractSpecTitle(specContent);
    const prTitle = `feat: ${specTitle.toLowerCase()}`;
    const prBody = [
      `This PR implements the feature described in the spec: \`${spec_path}\``,
      ``,
      `Generated by Autocatalyst.`,
    ].join('\n');

    // Push the branch
    try {
      await this.execFn('git', ['push', 'origin', branch], { cwd: workspace_path });
    } catch (err) {
      this.logger.error(
        { event: 'pr.creation_failed', error: String(err), step: 'push', branch },
        'git push failed',
      );
      throw new Error(`git push failed: ${String(err)}`);
    }

    // Create the PR
    let prUrl: string;
    try {
      const { stdout } = await this.execFn(
        'gh',
        ['pr', 'create', '--title', prTitle, '--body', prBody],
        { cwd: workspace_path },
      );
      prUrl = stdout.trim();
    } catch (err) {
      this.logger.error(
        { event: 'pr.creation_failed', error: String(err), step: 'pr_create', branch },
        'gh pr create failed',
      );
      throw new Error(`gh pr create failed: ${String(err)}`);
    }

    this.logger.info(
      { event: 'pr.created', pr_url: prUrl, branch, spec_title: specTitle },
      'PR created',
    );
    return prUrl;
  }
}
