import type { CumulativeImplementationSummary } from './implementation-summary.js';
import { MissingCumulativeImplementationSummaryError } from './implementation-summary.js';
import type { PullRequestContent } from './code-host.js';
import { deriveConventionalTitle } from './conventional-title.js';

export interface BuildPullRequestContentInput {
  readonly workKind: string;
  readonly issueUrl?: string | null;
  readonly cumulativeSummary: CumulativeImplementationSummary;
  readonly reconciledSummary?: string | null;
  readonly titleSubject?: string | null;
}

export function buildPullRequestContent(input: BuildPullRequestContentInput): PullRequestContent {
  if (!input.cumulativeSummary) {
    throw new MissingCumulativeImplementationSummaryError();
  }

  const title = deriveConventionalTitle({
    workKind: input.workKind,
    titleSubject: input.titleSubject ?? null,
    reconciledSummary: input.reconciledSummary ?? null,
    cumulativeSummary: input.cumulativeSummary.cumulativeSummary
  });

  if (title === null) {
    throw new Error(`Work kind '${input.workKind}' does not produce a pull request.`);
  }

  const summaryText = input.reconciledSummary?.trim() || input.cumulativeSummary.cumulativeSummary;

  const sections: string[] = [];

  sections.push('## Summary\n');
  sections.push(summaryText);

  if (input.issueUrl) {
    sections.push(`\n**Issue:** ${input.issueUrl}`);
  }

  if (input.cumulativeSummary.changedFiles.length > 0) {
    sections.push('\n## Changed files\n');
    sections.push(input.cumulativeSummary.changedFiles.map((f) => `- \`${f}\``).join('\n'));
  }

  if (input.cumulativeSummary.validationSummary.length > 0) {
    sections.push('\n## Validation\n');
    sections.push(input.cumulativeSummary.validationSummary.map((v) => `- ${v}`).join('\n'));
  }

  if (input.cumulativeSummary.followUps.length > 0) {
    sections.push('\n## Follow-ups and non-goals\n');
    sections.push(input.cumulativeSummary.followUps.map((f) => `- ${f}`).join('\n'));
  }

  if (input.cumulativeSummary.nonGoals.length > 0) {
    if (input.cumulativeSummary.followUps.length === 0) {
      sections.push('\n## Non-goals\n');
    }
    sections.push(input.cumulativeSummary.nonGoals.map((g) => `- ${g}`).join('\n'));
  }

  sections.push('\n---\n*Generated by Autocatalyst*');

  return {
    title,
    body: sections.join('\n')
  };
}
