import type { CumulativeImplementationSummary } from './implementation-summary.js';
import { MissingCumulativeImplementationSummaryError } from './implementation-summary.js';
import type { PullRequestContent } from './code-host.js';
import { deriveConventionalTitle } from './conventional-title.js';

const LEGACY_COUNT_PLACEHOLDER_PATTERN = /^(?:round\s+\d+:\s*)?\d+\s+file\(s\) changed$/iu;
export const LEGACY_TEXT_PLACEHOLDER_PATTERN = /^round\s+\d+:\s*implementation passed review$/iu;

function normalizeRenderableChangedFile(path: string): string | null {
  const normalized = path.replace(/\\/gu, '/').replace(/^\.\//u, '').trim();
  if (normalized.length === 0) return null;
  if (LEGACY_COUNT_PLACEHOLDER_PATTERN.test(normalized)) return null;
  if (normalized.startsWith('/')) return null;
  if (normalized.split('/').some((segment) => segment.length === 0 || segment === '.' || segment === '..')) return null;
  return normalized;
}

function renderableChangedFiles(paths: readonly string[]): readonly string[] {
  return [...new Set(paths.map(normalizeRenderableChangedFile).filter((path): path is string => path !== null))]
    .sort((a, b) => a.localeCompare(b));
}

export interface BuildPullRequestContentInput {
  readonly workKind: string;
  readonly issueUrl?: string | null;
  readonly cumulativeSummary: CumulativeImplementationSummary;
  readonly reconciledSummary?: string | null;
  readonly titleSubject?: string | null;
}

export function buildPullRequestContent(input: BuildPullRequestContentInput): PullRequestContent {
  if (!input.cumulativeSummary) {
    throw new MissingCumulativeImplementationSummaryError();
  }

  const changedFiles = renderableChangedFiles(input.cumulativeSummary.changedFiles);
  const title = deriveConventionalTitle({
    workKind: input.workKind,
    titleSubject: input.titleSubject ?? null,
    reconciledSummary: input.reconciledSummary ?? null,
    cumulativeSummary: input.cumulativeSummary.cumulativeSummary,
    changedFiles
  });

  if (title === null) {
    throw new Error(`Work kind '${input.workKind}' does not produce a pull request.`);
  }

  const rawCumulativeSummary = LEGACY_TEXT_PLACEHOLDER_PATTERN.test(input.cumulativeSummary.cumulativeSummary.trim())
    ? ''
    : input.cumulativeSummary.cumulativeSummary;
  const summaryText = input.reconciledSummary?.trim() || rawCumulativeSummary;

  const sections: string[] = [];

  sections.push('## Summary\n');
  sections.push(summaryText);

  if (input.issueUrl) {
    sections.push(`\n**Issue:** ${input.issueUrl}`);
  }

  if (changedFiles.length > 0) {
    sections.push('\n## Changed files\n');
    sections.push(changedFiles.map((f) => `- \`${f}\``).join('\n'));
  }

  if (input.cumulativeSummary.validationSummary.length > 0) {
    sections.push('\n## Validation\n');
    sections.push(input.cumulativeSummary.validationSummary.map((v) => `- ${v}`).join('\n'));
  }

  if (input.cumulativeSummary.followUps.length > 0) {
    sections.push('\n## Follow-ups and non-goals\n');
    sections.push(input.cumulativeSummary.followUps.map((f) => `- ${f}`).join('\n'));
  }

  if (input.cumulativeSummary.nonGoals.length > 0) {
    if (input.cumulativeSummary.followUps.length === 0) {
      sections.push('\n## Non-goals\n');
    }
    sections.push(input.cumulativeSummary.nonGoals.map((g) => `- ${g}`).join('\n'));
  }

  sections.push('\n---\n*Generated by Autocatalyst*');

  return {
    title,
    body: sections.join('\n')
  };
}
